CONFIG_ZMK_KEYBOARD_NAME="desolation" 

# ----------------------------------------------
# ----------------------------------------------

# BLUETOOTH - settings
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# Signal power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Sleep settings
CONFIG_ZMK_SLEEP=y

# Idle timeout
# 10 hours = 36,000,000 ms
# 2.5 hours = 9,000,000 ms
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000

# Deep sleep
CONFIG_ZMK_PM_SOFT_OFF=y

# ----------------------------------------------
# ----------------------------------------------

# DEBOUNCE
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# ----------------------------------------------
# ----------------------------------------------

# MACROS - Queue size for large macros
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

# ----------------------------------------------
# ----------------------------------------------

# MOUSE
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# ----------------------------------------------
# ----------------------------------------------

# # Enable nice!view
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
# CONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_26=y
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_WIDGET_WPM_STATUS=n
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
# CONFIG_ZMK_DISPLAY_INVERT=y
